import type { BibliotecaCategoriaCompleta } from '@/lib/types';

/** Catálogos adicionales (equipos, seguridad, inventario, etc.) */
export const BIBLIOTECA_FALLBACK_EXT: BibliotecaCategoriaCompleta[] = [
  {
    id: 'fb-clima',
    slug: 'clima_guardia',
    nombre: 'Clima (guardia)',
    descripcion: null,
    modulo: 'operaciones',
    orden: 110,
    activo: true,
    created_at: '',
    updated_at: '',
    variables: [
      { id: 'c1', categoria_id: 'fb-clima', clave: 'despejado', etiqueta: 'Despejado', valor: 'despejado', unidad: null, descripcion: null, orden: 1, activo: true, metadata: { display_label: '☀️ Despejado' }, created_at: '', updated_at: '' },
      { id: 'c2', categoria_id: 'fb-clima', clave: 'nublado', etiqueta: 'Nublado', valor: 'nublado', unidad: null, descripcion: null, orden: 2, activo: true, metadata: { display_label: '⛅ Nublado' }, created_at: '', updated_at: '' },
      { id: 'c3', categoria_id: 'fb-clima', clave: 'lluvia', etiqueta: 'Lluvia', valor: 'lluvia', unidad: null, descripcion: null, orden: 3, activo: true, metadata: { display_label: '🌧️ Lluvia' }, created_at: '', updated_at: '' },
      { id: 'c4', categoria_id: 'fb-clima', clave: 'tormenta', etiqueta: 'Tormenta', valor: 'tormenta', unidad: null, descripcion: null, orden: 4, activo: true, metadata: { display_label: '⛈️ Tormenta' }, created_at: '', updated_at: '' },
      { id: 'c5', categoria_id: 'fb-clima', clave: 'neblina', etiqueta: 'Neblina', valor: 'neblina', unidad: null, descripcion: null, orden: 5, activo: true, metadata: { display_label: '🌫️ Neblina' }, created_at: '', updated_at: '' },
    ],
  },
  {
    id: 'fb-equipos-tipo',
    slug: 'equipos_tipo',
    nombre: 'Tipos de equipo',
    descripcion: null,
    modulo: 'mina',
    orden: 120,
    activo: true,
    created_at: '',
    updated_at: '',
    variables: (
      [
        ['compresor', 'Compresor'],
        ['perforadora', 'Perforadora'],
        ['volqueta', 'Volqueta'],
        ['bomba', 'Bomba'],
        ['generador', 'Generador'],
        ['ventilador', 'Ventilador'],
        ['otro', 'Otro'],
      ] as const
    ).map(([valor, etiqueta], i) => ({
      id: `et${i}`,
      categoria_id: 'fb-equipos-tipo',
      clave: valor,
      etiqueta,
      valor,
      unidad: null,
      descripcion: null,
      orden: i + 1,
      activo: true,
      metadata: {},
      created_at: '',
      updated_at: '',
    })),
  },
  {
    id: 'fb-equipos-estado',
    slug: 'equipos_estado',
    nombre: 'Estado de equipo',
    descripcion: null,
    modulo: 'mina',
    orden: 121,
    activo: true,
    created_at: '',
    updated_at: '',
    variables: [
      { id: 'ee1', categoria_id: 'fb-equipos-estado', clave: 'operativo', etiqueta: 'Operativo', valor: 'operativo', unidad: null, descripcion: null, orden: 1, activo: true, metadata: {}, created_at: '', updated_at: '' },
      { id: 'ee2', categoria_id: 'fb-equipos-estado', clave: 'en_mantenimiento', etiqueta: 'Mantenimiento', valor: 'en_mantenimiento', unidad: null, descripcion: null, orden: 2, activo: true, metadata: {}, created_at: '', updated_at: '' },
      { id: 'ee3', categoria_id: 'fb-equipos-estado', clave: 'fuera_servicio', etiqueta: 'Fuera de servicio', valor: 'fuera_servicio', unidad: null, descripcion: null, orden: 3, activo: true, metadata: {}, created_at: '', updated_at: '' },
      { id: 'ee4', categoria_id: 'fb-equipos-estado', clave: 'en_reparacion', etiqueta: 'En reparación', valor: 'en_reparacion', unidad: null, descripcion: null, orden: 4, activo: true, metadata: {}, created_at: '', updated_at: '' },
    ],
  },
  {
    id: 'fb-inv-cat',
    slug: 'inventario_categoria',
    nombre: 'Categorías inventario',
    descripcion: null,
    modulo: 'admin',
    orden: 140,
    activo: true,
    created_at: '',
    updated_at: '',
    variables: [
      { id: 'ic1', categoria_id: 'fb-inv-cat', clave: 'explosivos', etiqueta: 'Explosivos', valor: 'explosivos', unidad: null, descripcion: null, orden: 1, activo: true, metadata: {}, created_at: '', updated_at: '' },
      { id: 'ic2', categoria_id: 'fb-inv-cat', clave: 'combustible', etiqueta: 'Combustible', valor: 'combustible', unidad: null, descripcion: null, orden: 2, activo: true, metadata: {}, created_at: '', updated_at: '' },
      { id: 'ic3', categoria_id: 'fb-inv-cat', clave: 'herramientas', etiqueta: 'Herramientas', valor: 'herramientas', unidad: null, descripcion: null, orden: 3, activo: true, metadata: {}, created_at: '', updated_at: '' },
      { id: 'ic4', categoria_id: 'fb-inv-cat', clave: 'epp', etiqueta: 'EPP', valor: 'epp', unidad: null, descripcion: null, orden: 4, activo: true, metadata: {}, created_at: '', updated_at: '' },
      { id: 'ic5', categoria_id: 'fb-inv-cat', clave: 'quimicos', etiqueta: 'Químicos', valor: 'quimicos', unidad: null, descripcion: null, orden: 5, activo: true, metadata: {}, created_at: '', updated_at: '' },
      { id: 'ic6', categoria_id: 'fb-inv-cat', clave: 'repuestos', etiqueta: 'Repuestos', valor: 'repuestos', unidad: null, descripcion: null, orden: 6, activo: true, metadata: {}, created_at: '', updated_at: '' },
      { id: 'ic7', categoria_id: 'fb-inv-cat', clave: 'otros', etiqueta: 'Otros', valor: 'otros', unidad: null, descripcion: null, orden: 7, activo: true, metadata: {}, created_at: '', updated_at: '' },
    ],
  },
  {
    id: 'fb-seg-tipo',
    slug: 'seguridad_tipo',
    nombre: 'Tipos (seguridad)',
    descripcion: null,
    modulo: 'mina',
    orden: 130,
    activo: true,
    created_at: '',
    updated_at: '',
    variables: [
      { id: 'st1', categoria_id: 'fb-seg-tipo', clave: 'mejora_infraestructura', etiqueta: 'Infraestructura', valor: 'mejora_infraestructura', unidad: null, descripcion: null, orden: 1, activo: true, metadata: {}, created_at: '', updated_at: '' },
      { id: 'st2', categoria_id: 'fb-seg-tipo', clave: 'mejora_proceso', etiqueta: 'Proceso', valor: 'mejora_proceso', unidad: null, descripcion: null, orden: 2, activo: true, metadata: {}, created_at: '', updated_at: '' },
      { id: 'st3', categoria_id: 'fb-seg-tipo', clave: 'incidente', etiqueta: 'Incidente', valor: 'incidente', unidad: null, descripcion: null, orden: 3, activo: true, metadata: {}, created_at: '', updated_at: '' },
      { id: 'st4', categoria_id: 'fb-seg-tipo', clave: 'inspeccion', etiqueta: 'Inspección', valor: 'inspeccion', unidad: null, descripcion: null, orden: 4, activo: true, metadata: {}, created_at: '', updated_at: '' },
      { id: 'st5', categoria_id: 'fb-seg-tipo', clave: 'capacitacion', etiqueta: 'Capacitación', valor: 'capacitacion', unidad: null, descripcion: null, orden: 5, activo: true, metadata: {}, created_at: '', updated_at: '' },
    ],
  },
  {
    id: 'fb-areas-op',
    slug: 'areas_operativas',
    nombre: 'Áreas operativas',
    descripcion: null,
    modulo: 'general',
    orden: 131,
    activo: true,
    created_at: '',
    updated_at: '',
    variables: [
      { id: 'ao1', categoria_id: 'fb-areas-op', clave: 'mina', etiqueta: 'Mina', valor: 'mina', unidad: null, descripcion: null, orden: 1, activo: true, metadata: {}, created_at: '', updated_at: '' },
      { id: 'ao2', categoria_id: 'fb-areas-op', clave: 'planta', etiqueta: 'Planta', valor: 'planta', unidad: null, descripcion: null, orden: 2, activo: true, metadata: {}, created_at: '', updated_at: '' },
      { id: 'ao3', categoria_id: 'fb-areas-op', clave: 'general', etiqueta: 'General', valor: 'general', unidad: null, descripcion: null, orden: 3, activo: true, metadata: {}, created_at: '', updated_at: '' },
    ],
  },
  {
    id: 'fb-inv-mov',
    slug: 'inventario_movimiento',
    nombre: 'Movimientos inventario',
    descripcion: null,
    modulo: 'admin',
    orden: 141,
    activo: true,
    created_at: '',
    updated_at: '',
    variables: [
      { id: 'im1', categoria_id: 'fb-inv-mov', clave: 'entrada', etiqueta: 'Entrada', valor: 'entrada', unidad: null, descripcion: null, orden: 1, activo: true, metadata: { display_label: '⬆ Entrada' }, created_at: '', updated_at: '' },
      { id: 'im2', categoria_id: 'fb-inv-mov', clave: 'salida', etiqueta: 'Salida', valor: 'salida', unidad: null, descripcion: null, orden: 2, activo: true, metadata: { display_label: '⬇ Salida' }, created_at: '', updated_at: '' },
      { id: 'im3', categoria_id: 'fb-inv-mov', clave: 'ajuste', etiqueta: 'Ajuste', valor: 'ajuste', unidad: null, descripcion: null, orden: 3, activo: true, metadata: { display_label: '↔ Ajuste' }, created_at: '', updated_at: '' },
    ],
  },
  {
    id: 'fb-inv-dest',
    slug: 'inventario_destino',
    nombre: 'Destino inventario',
    descripcion: null,
    modulo: 'admin',
    orden: 142,
    activo: true,
    created_at: '',
    updated_at: '',
    variables: [
      { id: 'id0', categoria_id: 'fb-inv-dest', clave: 'sin_ubicacion', etiqueta: 'Sin ubicación', valor: '', unidad: null, descripcion: null, orden: 0, activo: true, metadata: {}, created_at: '', updated_at: '' },
      { id: 'id1', categoria_id: 'fb-inv-dest', clave: 'mina', etiqueta: 'Mina', valor: 'mina', unidad: null, descripcion: null, orden: 1, activo: true, metadata: {}, created_at: '', updated_at: '' },
      { id: 'id2', categoria_id: 'fb-inv-dest', clave: 'planta', etiqueta: 'Planta', valor: 'planta', unidad: null, descripcion: null, orden: 2, activo: true, metadata: {}, created_at: '', updated_at: '' },
      { id: 'id3', categoria_id: 'fb-inv-dest', clave: 'general', etiqueta: 'General', valor: 'general', unidad: null, descripcion: null, orden: 3, activo: true, metadata: {}, created_at: '', updated_at: '' },
    ],
  },
  {
    id: 'fb-seg-pri',
    slug: 'seguridad_prioridad',
    nombre: 'Prioridad (seguridad)',
    descripcion: null,
    modulo: 'mina',
    orden: 132,
    activo: true,
    created_at: '',
    updated_at: '',
    variables: [
      { id: 'sp1', categoria_id: 'fb-seg-pri', clave: 'baja', etiqueta: 'Baja', valor: 'baja', unidad: null, descripcion: null, orden: 1, activo: true, metadata: {}, created_at: '', updated_at: '' },
      { id: 'sp2', categoria_id: 'fb-seg-pri', clave: 'normal', etiqueta: 'Normal', valor: 'normal', unidad: null, descripcion: null, orden: 2, activo: true, metadata: {}, created_at: '', updated_at: '' },
      { id: 'sp3', categoria_id: 'fb-seg-pri', clave: 'alta', etiqueta: 'Alta', valor: 'alta', unidad: null, descripcion: null, orden: 3, activo: true, metadata: {}, created_at: '', updated_at: '' },
      { id: 'sp4', categoria_id: 'fb-seg-pri', clave: 'critica', etiqueta: 'Crítica', valor: 'critica', unidad: null, descripcion: null, orden: 4, activo: true, metadata: {}, created_at: '', updated_at: '' },
    ],
  },
  {
    id: 'fb-seg-est',
    slug: 'seguridad_estado',
    nombre: 'Estado (seguridad)',
    descripcion: null,
    modulo: 'mina',
    orden: 133,
    activo: true,
    created_at: '',
    updated_at: '',
    variables: [
      { id: 'se1', categoria_id: 'fb-seg-est', clave: 'reportado', etiqueta: 'Reportado', valor: 'reportado', unidad: null, descripcion: null, orden: 1, activo: true, metadata: {}, created_at: '', updated_at: '' },
      { id: 'se2', categoria_id: 'fb-seg-est', clave: 'en_proceso', etiqueta: 'En proceso', valor: 'en_proceso', unidad: null, descripcion: null, orden: 2, activo: true, metadata: {}, created_at: '', updated_at: '' },
      { id: 'se3', categoria_id: 'fb-seg-est', clave: 'completado', etiqueta: 'Completado', valor: 'completado', unidad: null, descripcion: null, orden: 3, activo: true, metadata: {}, created_at: '', updated_at: '' },
      { id: 'se4', categoria_id: 'fb-seg-est', clave: 'descartado', etiqueta: 'Descartado', valor: 'descartado', unidad: null, descripcion: null, orden: 4, activo: true, metadata: {}, created_at: '', updated_at: '' },
    ],
  },
  {
    id: 'fb-proc-tipo',
    slug: 'procesamiento_tipo',
    nombre: 'Procesos (planta)',
    descripcion: null,
    modulo: 'planta',
    orden: 150,
    activo: true,
    created_at: '',
    updated_at: '',
    variables: [
      { id: 'pt1', categoria_id: 'fb-proc-tipo', clave: 'molienda', etiqueta: 'Molienda', valor: 'molienda', unidad: null, descripcion: null, orden: 1, activo: true, metadata: {}, created_at: '', updated_at: '' },
      { id: 'pt2', categoria_id: 'fb-proc-tipo', clave: 'concentracion', etiqueta: 'Concentración', valor: 'concentracion', unidad: null, descripcion: null, orden: 2, activo: true, metadata: {}, created_at: '', updated_at: '' },
      { id: 'pt3', categoria_id: 'fb-proc-tipo', clave: 'amalgamacion', etiqueta: 'Amalgamación', valor: 'amalgamacion', unidad: null, descripcion: null, orden: 3, activo: true, metadata: {}, created_at: '', updated_at: '' },
      { id: 'pt4', categoria_id: 'fb-proc-tipo', clave: 'cianuracion', etiqueta: 'Cianuración', valor: 'cianuracion', unidad: null, descripcion: null, orden: 4, activo: true, metadata: {}, created_at: '', updated_at: '' },
      { id: 'pt5', categoria_id: 'fb-proc-tipo', clave: 'flotacion', etiqueta: 'Flotación', valor: 'flotacion', unidad: null, descripcion: null, orden: 5, activo: true, metadata: {}, created_at: '', updated_at: '' },
      { id: 'pt6', categoria_id: 'fb-proc-tipo', clave: 'otro', etiqueta: 'Otro', valor: 'otro', unidad: null, descripcion: null, orden: 6, activo: true, metadata: {}, created_at: '', updated_at: '' },
    ],
  },
  {
    id: 'fb-proc-est',
    slug: 'procesamiento_estado',
    nombre: 'Estado procesamiento',
    descripcion: null,
    modulo: 'planta',
    orden: 151,
    activo: true,
    created_at: '',
    updated_at: '',
    variables: [
      { id: 'pe1', categoria_id: 'fb-proc-est', clave: 'en_proceso', etiqueta: 'En proceso', valor: 'en_proceso', unidad: null, descripcion: null, orden: 1, activo: true, metadata: {}, created_at: '', updated_at: '' },
      { id: 'pe2', categoria_id: 'fb-proc-est', clave: 'completado', etiqueta: 'Completado', valor: 'completado', unidad: null, descripcion: null, orden: 2, activo: true, metadata: {}, created_at: '', updated_at: '' },
      { id: 'pe3', categoria_id: 'fb-proc-est', clave: 'enviado_a_quemada', etiqueta: 'Enviado a quemada', valor: 'enviado_a_quemada', unidad: null, descripcion: null, orden: 3, activo: true, metadata: {}, created_at: '', updated_at: '' },
    ],
  },
  {
    id: 'fb-compras-pri',
    slug: 'compras_prioridad',
    nombre: 'Prioridad compras',
    descripcion: null,
    modulo: 'admin',
    orden: 160,
    activo: true,
    created_at: '',
    updated_at: '',
    variables: [
      { id: 'cp1', categoria_id: 'fb-compras-pri', clave: 'baja', etiqueta: 'Baja', valor: 'baja', unidad: null, descripcion: null, orden: 1, activo: true, metadata: {}, created_at: '', updated_at: '' },
      { id: 'cp2', categoria_id: 'fb-compras-pri', clave: 'normal', etiqueta: 'Normal', valor: 'normal', unidad: null, descripcion: null, orden: 2, activo: true, metadata: {}, created_at: '', updated_at: '' },
      { id: 'cp3', categoria_id: 'fb-compras-pri', clave: 'alta', etiqueta: 'Alta', valor: 'alta', unidad: null, descripcion: null, orden: 3, activo: true, metadata: {}, created_at: '', updated_at: '' },
      { id: 'cp4', categoria_id: 'fb-compras-pri', clave: 'urgente', etiqueta: 'Urgente', valor: 'urgente', unidad: null, descripcion: null, orden: 4, activo: true, metadata: {}, created_at: '', updated_at: '' },
    ],
  },
];
