import { BIBLIOTECA_FALLBACK_EXT } from '@/lib/biblioteca-fallbacks-ext';
import type { BibliotecaCategoriaCompleta } from '@/lib/types';

const FALLBACK_BIBLIOTECA_BASE: BibliotecaCategoriaCompleta[] = [
  {
    id: 'fallback-areas',
    slug: 'areas_nomina',
    nombre: 'Áreas de nómina',
    descripcion: null,
    modulo: 'nomina',
    orden: 10,
    activo: true,
    created_at: '',
    updated_at: '',
    variables: [
      { id: '1', categoria_id: 'fallback-areas', clave: 'mina', etiqueta: 'Mina', valor: 'mina', unidad: null, descripcion: null, orden: 1, activo: true, metadata: {}, created_at: '', updated_at: '' },
      { id: '2', categoria_id: 'fallback-areas', clave: 'planta', etiqueta: 'Molinos / Planta', valor: 'planta', unidad: null, descripcion: null, orden: 2, activo: true, metadata: {}, created_at: '', updated_at: '' },
      { id: '3', categoria_id: 'fallback-areas', clave: 'administracion', etiqueta: 'Administración', valor: 'administracion', unidad: null, descripcion: null, orden: 3, activo: true, metadata: {}, created_at: '', updated_at: '' },
      { id: '4', categoria_id: 'fallback-areas', clave: 'seguridad', etiqueta: 'Seguridad', valor: 'seguridad', unidad: null, descripcion: null, orden: 4, activo: true, metadata: {}, created_at: '', updated_at: '' },
      { id: '5', categoria_id: 'fallback-areas', clave: 'transporte', etiqueta: 'Transporte', valor: 'transporte', unidad: null, descripcion: null, orden: 5, activo: true, metadata: {}, created_at: '', updated_at: '' },
    ],
  },
  {
    id: 'fallback-cargos',
    slug: 'cargos',
    nombre: 'Cargos',
    descripcion: null,
    modulo: 'nomina',
    orden: 20,
    activo: true,
    created_at: '',
    updated_at: '',
    variables: ['Capataz', 'Palero', 'Cocinero', 'Operador', 'Ayudante'].map((e, i) => ({
      id: `c${i}`,
      categoria_id: 'fallback-cargos',
      clave: e.toLowerCase().replace(/\s+/g, '_'),
      etiqueta: e,
      valor: e,
      unidad: null,
      descripcion: null,
      orden: i,
      activo: true,
      metadata: {},
      created_at: '',
      updated_at: '',
    })),
  },
  {
    id: 'fallback-asignacion',
    slug: 'asignacion_nomina',
    nombre: 'Asignación nómina',
    descripcion: null,
    modulo: 'nomina',
    orden: 30,
    activo: true,
    created_at: '',
    updated_at: '',
    variables: [
      { id: 'a1', categoria_id: 'fallback-asignacion', clave: 'vertical_1', etiqueta: 'Vertical 1', valor: 'Vertical 1', unidad: null, descripcion: null, orden: 1, activo: true, metadata: {}, created_at: '', updated_at: '' },
      { id: 'a2', categoria_id: 'fallback-asignacion', clave: 'vertical_2', etiqueta: 'Vertical 2', valor: 'Vertical 2', unidad: null, descripcion: null, orden: 2, activo: true, metadata: {}, created_at: '', updated_at: '' },
      { id: 'a3', categoria_id: 'fallback-asignacion', clave: 'vertical_3', etiqueta: 'Vertical 3', valor: 'Vertical 3', unidad: null, descripcion: null, orden: 3, activo: true, metadata: {}, created_at: '', updated_at: '' },
      { id: 'a4', categoria_id: 'fallback-asignacion', clave: 'vertical_1pd', etiqueta: 'Vertical 1PD', valor: 'Vertical 1PD', unidad: null, descripcion: null, orden: 4, activo: true, metadata: {}, created_at: '', updated_at: '' },
    ],
  },
  {
    id: 'fallback-ubicaciones',
    slug: 'ubicaciones_laborales',
    nombre: 'Ubicaciones laborales',
    descripcion: null,
    modulo: 'nomina',
    orden: 40,
    activo: true,
    created_at: '',
    updated_at: '',
    variables: [
      { id: 'u1', categoria_id: 'fallback-ubicaciones', clave: 'mina_belen', etiqueta: 'Mina Belén', valor: 'Mina Belén', unidad: null, descripcion: null, orden: 1, activo: true, metadata: { areas: ['mina'] }, created_at: '', updated_at: '' },
      { id: 'u2', categoria_id: 'fallback-ubicaciones', clave: 'mina_la_fe', etiqueta: 'Mina La Fé', valor: 'Mina La Fé', unidad: null, descripcion: null, orden: 2, activo: true, metadata: { areas: ['mina'] }, created_at: '', updated_at: '' },
      { id: 'u3', categoria_id: 'fallback-ubicaciones', clave: 'molino_la_fe', etiqueta: 'Molino La Fé', valor: 'Molino La Fé', unidad: null, descripcion: null, orden: 3, activo: true, metadata: { areas: ['planta'] }, created_at: '', updated_at: '' },
      { id: 'u4', categoria_id: 'fallback-ubicaciones', clave: 'administracion', etiqueta: 'Administración', valor: 'Administración', unidad: null, descripcion: null, orden: 4, activo: true, metadata: { areas: ['administracion'], default_for_area: 'administracion' }, created_at: '', updated_at: '' },
      { id: 'u5', categoria_id: 'fallback-ubicaciones', clave: 'oficina_central', etiqueta: 'Oficina central', valor: 'Oficina central', unidad: null, descripcion: null, orden: 5, activo: true, metadata: { areas: ['administracion'] }, created_at: '', updated_at: '' },
      { id: 'u6', categoria_id: 'fallback-ubicaciones', clave: 'seg_mina', etiqueta: 'Seguridad — Mina Belén', valor: 'Seguridad — Mina Belén', unidad: null, descripcion: null, orden: 6, activo: true, metadata: { areas: ['seguridad'], default_for_area: 'seguridad' }, created_at: '', updated_at: '' },
      { id: 'u7', categoria_id: 'fallback-ubicaciones', clave: 'transporte', etiqueta: 'Transporte', valor: 'Transporte', unidad: null, descripcion: null, orden: 7, activo: true, metadata: { areas: ['transporte'], default_for_area: 'transporte' }, created_at: '', updated_at: '' },
    ],
  },
  {
    id: 'fallback-esquemas',
    slug: 'esquemas_rotacion',
    nombre: 'Esquemas de rotación',
    descripcion: null,
    modulo: 'nomina',
    orden: 50,
    activo: true,
    created_at: '',
    updated_at: '',
    variables: [
      { id: 'e1', categoria_id: 'fallback-esquemas', clave: 'FIJO_SEMANAL', etiqueta: 'Fijo semanal', valor: 'FIJO_SEMANAL', unidad: 'días', descripcion: null, orden: 1, activo: true, metadata: { areas: ['mina', 'planta', 'administracion', 'seguridad', 'transporte'] }, created_at: '', updated_at: '' },
      { id: 'e2', categoria_id: 'fallback-esquemas', clave: 'MINA_2X1', etiqueta: 'Mina 2×1', valor: 'MINA_2X1', unidad: 'días', descripcion: null, orden: 2, activo: true, metadata: { areas: ['mina'], default_for_area: 'mina' }, created_at: '', updated_at: '' },
      { id: 'e3', categoria_id: 'fallback-esquemas', clave: 'MINA_ROTATIVA_3G', etiqueta: 'Mina 3G', valor: 'MINA_ROTATIVA_3G', unidad: 'días', descripcion: null, orden: 3, activo: true, metadata: { areas: ['mina'] }, created_at: '', updated_at: '' },
      { id: 'e4', categoria_id: 'fallback-esquemas', clave: 'MOLINO_FIJO', etiqueta: 'Molino fijo', valor: 'MOLINO_FIJO', unidad: 'días', descripcion: null, orden: 4, activo: true, metadata: { areas: ['planta'] }, created_at: '', updated_at: '' },
      { id: 'e5', categoria_id: 'fallback-esquemas', clave: 'MOLINO_ROTATIVO', etiqueta: 'Molino rotativo', valor: 'MOLINO_ROTATIVO', unidad: 'días', descripcion: null, orden: 5, activo: true, metadata: { areas: ['planta'], default_for_area: 'planta' }, created_at: '', updated_at: '' },
      { id: 'e6', categoria_id: 'fallback-esquemas', clave: 'MOLINO_15X15', etiqueta: 'Molino 15×15', valor: 'MOLINO_15X15', unidad: 'días', descripcion: null, orden: 6, activo: true, metadata: { areas: ['planta'] }, created_at: '', updated_at: '' },
    ],
  },
  {
    id: 'fallback-minas',
    slug: 'minas',
    nombre: 'Minas',
    descripcion: null,
    modulo: 'mina',
    orden: 60,
    activo: true,
    created_at: '',
    updated_at: '',
    variables: [
      { id: 'm1', categoria_id: 'fallback-minas', clave: 'mina_belen', etiqueta: 'Mina Belén', valor: 'Mina Belén', unidad: null, descripcion: null, orden: 1, activo: true, metadata: {}, created_at: '', updated_at: '' },
      { id: 'm2', categoria_id: 'fallback-minas', clave: 'mina_la_fe', etiqueta: 'Mina La Fé', valor: 'Mina La Fé', unidad: null, descripcion: null, orden: 2, activo: true, metadata: {}, created_at: '', updated_at: '' },
    ],
  },
  {
    id: 'fallback-verticales',
    slug: 'verticales_voladura',
    nombre: 'Verticales (voladuras)',
    descripcion: null,
    modulo: 'mina',
    orden: 70,
    activo: true,
    created_at: '',
    updated_at: '',
    variables: [
      { id: 'v1', categoria_id: 'fallback-verticales', clave: 'vertical_1', etiqueta: 'Vertical 1', valor: 'Vertical 1', unidad: null, descripcion: null, orden: 1, activo: true, metadata: {}, created_at: '', updated_at: '' },
      { id: 'v2', categoria_id: 'fallback-verticales', clave: 'vertical_2', etiqueta: 'Vertical 2', valor: 'Vertical 2', unidad: null, descripcion: null, orden: 2, activo: true, metadata: {}, created_at: '', updated_at: '' },
      { id: 'v3', categoria_id: 'fallback-verticales', clave: 'vertical_3', etiqueta: 'Vertical 3', valor: 'Vertical 3', unidad: null, descripcion: null, orden: 3, activo: true, metadata: {}, created_at: '', updated_at: '' },
    ],
  },
  {
    id: 'fallback-turnos',
    slug: 'turnos',
    nombre: 'Turnos',
    descripcion: null,
    modulo: 'mina',
    orden: 80,
    activo: true,
    created_at: '',
    updated_at: '',
    variables: [
      { id: 't1', categoria_id: 'fallback-turnos', clave: 'dia', etiqueta: 'Día', valor: 'dia', unidad: null, descripcion: null, orden: 1, activo: true, metadata: {}, created_at: '', updated_at: '' },
      { id: 't2', categoria_id: 'fallback-turnos', clave: 'noche', etiqueta: 'Noche', valor: 'noche', unidad: null, descripcion: null, orden: 2, activo: true, metadata: {}, created_at: '', updated_at: '' },
      { id: 't3', categoria_id: 'fallback-turnos', clave: 'completo', etiqueta: 'Completo', valor: 'completo', unidad: null, descripcion: null, orden: 3, activo: true, metadata: {}, created_at: '', updated_at: '' },
    ],
  },
  {
    id: 'fallback-molinos',
    slug: 'molinos',
    nombre: 'Molinos / planta',
    descripcion: null,
    modulo: 'planta',
    orden: 100,
    activo: true,
    created_at: '',
    updated_at: '',
    variables: [
      { id: 'mo1', categoria_id: 'fallback-molinos', clave: 'molino_la_fe', etiqueta: 'Molino La Fé', valor: 'Molino La Fé', unidad: null, descripcion: null, orden: 1, activo: true, metadata: {}, created_at: '', updated_at: '' },
    ],
  },
];

/** Catálogo embebido si Supabase aún no tiene datos (misma semilla que las migraciones). */
export const FALLBACK_BIBLIOTECA_CATALOGO: BibliotecaCategoriaCompleta[] = [
  ...FALLBACK_BIBLIOTECA_BASE,
  ...BIBLIOTECA_FALLBACK_EXT,
];
