import type { ReconciliationRuleDef } from '@/lib/reconciliation/types';

export const RECONCILIATION_RULES: ReconciliationRuleDef[] = [
  {
    id: 'sacos_mina_planta',
    label: 'Sacos mina → planta',
    description: 'Sacos extraídos vs sacos procesados en planta',
    severity: 'high',
    toleranceKey: 'tolSacosMinaPlantaPct',
    compare: 'pct_diff',
    drillDown: ['dia', 'mina', 'registro'],
    origenA: 'reportes_extraccion · Σ sacos_extraidos',
    origenB: 'Balance · producción · Σ sacos',
    unidadA: 'sacos',
    unidadB: 'sacos',
  },
  {
    id: 'oro_planta_quemado',
    label: 'Oro planta vs quemado',
    description: 'Oro recuperado en planta vs oro en quemado',
    severity: 'high',
    toleranceKey: 'tolOroPlantaQuemadoPct',
    compare: 'pct_diff',
    drillDown: ['dia', 'registro'],
    origenA: 'Balance · producción · Σ oro_recuperado_g',
    origenB: 'reportes_quemado · Σ total_oro_g',
    unidadA: 'g',
    unidadB: 'g',
  },
  {
    id: 'recovery_ley',
    label: 'Recovery vs meta',
    description: 'Recovery efectivo (oro/ley esperada) vs meta biblioteca',
    severity: 'medium',
    compare: 'gte',
    drillDown: ['dia'],
    origenA: 'Calculado · oro planta ÷ (ton × ley cabeza)',
    origenB: 'Biblioteca · meta_recovery_pct',
    unidadA: '%',
    unidadB: '%',
  },
  {
    id: 'ingreso_vs_gastos',
    label: 'Ingresos vs gastos totales',
    description: 'Ingreso oro+arenas menos nómina y gastos operativos',
    severity: 'high',
    compare: 'gte',
    drillDown: ['semana'],
    origenA: 'Motor · (oro×precio + arenas) − (nómina + gastos)',
    origenB: 'Biblioteca · meta_utilidad_min_usd',
    unidadA: 'USD',
    unidadB: 'USD',
  },
  {
    id: 'margen_meta',
    label: 'Margen vs meta',
    description: 'Margen % del periodo vs meta configurada',
    severity: 'medium',
    compare: 'gte',
    drillDown: ['semana'],
    origenA: 'Motor · margen % del periodo',
    origenB: 'Biblioteca · meta_margen_pct',
    unidadA: '%',
    unidadB: '%',
  },
  {
    id: 'costo_por_gramo',
    label: 'Costo por gramo',
    description: 'Costo/g vs meta máxima (si está definida)',
    severity: 'medium',
    compare: 'lte',
    drillDown: ['dia'],
    origenA: 'Motor · (nómina + gastos) ÷ oro planta',
    origenB: 'Biblioteca · meta_costo_por_gramo_usd',
    unidadA: 'USD/g',
    unidadB: 'USD/g',
  },
  {
    id: 'nomina_registros_semanas',
    label: 'Nómina: detalle vs cierres',
    description:
      'Compara cuánto suman los pagos registrados día a día frente al total de las semanas ya cerradas en el mismo periodo.',
    severity: 'medium',
    toleranceKey: 'tolNominaVsSemanasPct',
    compare: 'pct_diff',
    drillDown: ['semana'],
    origenA: 'Reportes de balance (pagos por registro)',
    origenB: 'Semanas cerradas en nómina',
    unidadA: 'USD',
    unidadB: 'USD',
  },
  {
    id: 'rpc_divergencia',
    label: 'Coherencia con Resumen RPC',
    description: 'Comparación ingreso motor vs get_rentabilidad',
    severity: 'low',
    toleranceKey: 'tolRpcIngresoPct',
    compare: 'pct_diff',
    drillDown: ['dia'],
    origenA: 'Motor reconciliación · ingreso bruto',
    origenB: 'RPC get_rentabilidad · ingreso_bruto_usd',
    unidadA: 'USD',
    unidadB: 'USD',
  },
];

export function getRuleDef(id: string): ReconciliationRuleDef | undefined {
  return RECONCILIATION_RULES.find((r) => r.id === id);
}
